#!/usr/bin/env sh
#
# Simple Pyhon script obfuscation.
# - Removes all comment lines (including #!)
#   and empty lines.
# - Compress the striped file with gzip
# - base64 encode the compressed file
#
# gzip and uuencode/uudecode are choosed because they
# are widley used linux tools.
#
# The Python script could be executed by
#      $ base64 -d FILE | gzip -d | python - ARGUMENTS
# where FILE is the file generated by this script and
# ARGUMENTS are the arguments used by the Python script.
#

if [ $# -ne 1 ]; then
  echo "missing argument: Python script name" >&2
  return 1
fi

# strip comment lines
grep -v '^ *#' "$1" |
# strip empty lines
grep -v '^$' |
# compress
gzip --stdout - |
# base64 encode
base64 - > "$1.base64"

echo "The compressed and encoded file is $1.base64"

